---
abstract: 'JSON Web Token (JWT) implementation'
author:
  - 'xaicron E<lt>xaicron@cpan.orgE<gt>'
build_requires:
  Test::Mock::Guard: 0.07
  Test::More: 0.98
  Test::Requires: 0.06
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JSON-WebToken
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  JSON::WebToken:
    file: lib/JSON/WebToken.pm
    version: 0.03
  JSON::WebToken::Crypt:
    file: lib/JSON/WebToken/Crypt.pm
    version: 0
  JSON::WebToken::Crypt::HMAC:
    file: lib/JSON/WebToken/Crypt/HMAC.pm
    version: 0
  JSON::WebToken::Crypt::RSA:
    file: lib/JSON/WebToken/Crypt/RSA.pm
    version: 0
requires:
  Carp: 0
  Class::Load: 0.19
  Digest::SHA: 5.71
  Exporter: 5.59
  JSON::XS: 0
  MIME::Base64: 3.13
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
