---
abstract: 'JSON Web Token (JWT) implementation'
author:
  - 'xaicron <xaicron@cpan.org>'
build_requires:
  Test::Mock::Guard: 0.07
  Test::More: 0.98
  Test::Requires: 0.06
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JSON-WebToken
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  JSON::WebToken:
    file: lib/JSON/WebToken.pm
    version: 0.08
  JSON::WebToken::Constants:
    file: lib/JSON/WebToken/Constants.pm
  JSON::WebToken::Crypt:
    file: lib/JSON/WebToken/Crypt.pm
  JSON::WebToken::Crypt::HMAC:
    file: lib/JSON/WebToken/Crypt/HMAC.pm
  JSON::WebToken::Crypt::RSA:
    file: lib/JSON/WebToken/Crypt/RSA.pm
  JSON::WebToken::Exception:
    file: lib/JSON/WebToken/Exception.pm
requires:
  Carp: 0
  Digest::SHA: 0
  Exporter: 0
  JSON: 0
  MIME::Base64: 0
  Module::Runtime: 0
  parent: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/xaicron/p5-JSON-WebToken/issues
  homepage: https://github.com/xaicron/p5-JSON-WebToken
  repository: git://github.com/xaicron/p5-JSON-WebToken.git
version: 0.08
x_authority: cpan:XAICRON
x_contributors:
  - 'Masaki Sawamura <sawamura.masaki@dena.jp>'
  - 'Ryo <ritou.06@gmail.com>'
  - 'xaicron <xaicron@gmail.com>'
